Post-part-44 dilution round 4: GPIO_EMUL kconfig candidate (135->136)
9th instance of the proven "invert depends on DT_HAS_ZEPHYR_..._ENABLED" *_EMUL shape,
confirmed genuine "undefined reference to __device_dts_ord_38" link error.